// @flow
export const FETCH_REQUEST: Type = 'FORM_COMPONENT/FETCH_REQUEST';
export const FETCH_SUCCESS: Type = 'FORM_COMPONENT/FETCH_SUCCESS';
export const FETCH_FAILURE: Type = 'FORM_COMPONENT/FETCH_FAILURE';
export const FETCH_CANCEL: Type = 'FORM_COMPONENT/FETCH_CANCEL';
